<?php
//zend by QQ:123456  商创网络  禁止倒卖 一经发现停止任何服务
$_LANG['ems'] = 'EMS express mail service';
$_LANG['ems_express_desc'] = 'EMS express mail service\'s description';
$_LANG['item_fee'] = 'Single commodity costs:';
$_LANG['base_fee'] = 'Cost less than 500g:';
$_LANG['step_fee'] = 'In addition, every less than or equal to 500g:';
$_LANG['shipping_print'] = "<table style=\"width:18.8cm\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td style=\"height:3.2cm;\">&nbsp;</td>\r\n  </tr>\r\n</table>\r\n<table style=\"width:18.8cm;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td style=\"width:8.9cm;\">\r\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n    <tr>\r\n    <td style=\"width:1.6cm; height:0.7cm;\">&nbsp;</td>\r\n    <td style=\"width:2.3cm;\">{\$shop_name}</td>\r\n    <td style=\"width:2cm;\">&nbsp;</td>\r\n    <td>{\$service_phone}</td>\r\n    </tr>\r\n    <tr>\r\n    <td colspan=\"4\" style=\"height:0.7cm; padding-left:1.6cm;\">{\$shop_name}</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td colspan=\"3\" style=\"height:1.7cm;\">{\$shop_address}</td>\r\n    </tr>\r\n    <tr>\r\n    <td colspan=\"3\" style=\"width:6.3cm; height:0.5cm;\"></td>\r\n    <td>&nbsp;</td>\r\n    </tr>\r\n    </table>\r\n    </td>\r\n    <td style=\"width:0.4cm;\"></td>\r\n    <td style=\"width:9.5cm;\">\r\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n    <tr>\r\n    <td style=\"width:1.6cm; height:0.7cm;\">&nbsp;</td>\r\n    <td style=\"width:2.3cm;\">{\$order.consignee}</td>\r\n    <td style=\"width:2cm;\">&nbsp;</td>\r\n    <td>{\$order.mobile}</td>\r\n    </tr>\r\n    <tr>\r\n    <td colspan=\"4\" style=\"height:0.7cm;\">&nbsp;</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td colspan=\"3\" style=\"height:1.7cm;\">{\$order.address}</td>\r\n    </tr>\r\n    <tr>\r\n    <td colspan=\"3\" style=\"width:6.3cm; height:0.5cm;\"></td>\r\n    <td>{\$order.zipcode}</td>\r\n    </tr>\r\n    </table>\r\n    </td>\r\n  </tr>\r\n</table>\r\n<table style=\"width:18.8cm\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td style=\"height:5.1cm;\">&nbsp;</td>\r\n  </tr>\r\n</table>";

?>
