<?php
//zend by QQ:123456  商创网络  禁止倒卖 一经发现停止任何服务
$_LANG['sto_express'] = 'Shen Tong shipping';
$_LANG['sto_express_desc'] = 'Cost of Jiang, Zhe, Hu region less than 1000g is less than 15 yuan/kg, other region 18 yuan/kg, more than 1000g is 5-6 yuan/kg, Yun Nan region is 8 yuan.';
$_LANG['item_fee'] = 'Single commodity costs:';
$_LANG['base_fee'] = 'Cost less than 1000g';
$_LANG['step_fee'] = 'Every less than or equal to 1000g:';
$_LANG['shipping_print'] = "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width:18.9cm;\">\r\n  <tr>\r\n    <td colspan=\"3\" style=\"height:2cm;\">&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td style=\"width:8cm; height:4cm; padding-top:0.3cm;\" align=\"center\" valign=\"middle\">\r\n     <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width:7.5cm;\" align=\"center\">\r\n  <tr>\r\n    <td style=\"width:2.3cm;\">&nbsp;</td>\r\n    <td style=\"height:1.5cm;\">{\$shop_address}</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:0.9cm;\">{\$shop_name}</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:0.9cm;\">{\$shop_name}</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:0.9cm;\">{\$service_phone}</td>\r\n  </tr>\r\n</table>\r\n\r\n    </td>\r\n    <td style=\"width:8cm; height:4cm; padding-top:0.3cm;\" align=\"center\" valign=\"middle\">\r\n    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"width:7.5cm;\" align=\"center\">\r\n  <tr>\r\n    <td style=\"width:2.3cm;\">&nbsp;</td>\r\n    <td style=\"height:1.5cm;\">{\$order.address}</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:0.9cm;\"></td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:0.9cm;\">{\$order.consignee}</td>\r\n  </tr>\r\n  <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:0.9cm;\">{\$order.tel}</td>\r\n  </tr>\r\n</table>\r\n    </td>\r\n    <td rowspan=\"2\" style=\"width:3cm;\">&nbsp;</td>\r\n  </tr>\r\n  <tr>\r\n    <td colspan=\"2\" style=\"height:3.5cm;\">&nbsp;</td>\r\n  </tr>\r\n</table>";

?>
