<?php
//zend by QQ:123456  商创网络  禁止倒卖 一经发现停止任何服务
$_LANG['zto'] = 'ZTO express';
$_LANG['zto_desc'] = 'Qualcomm\'s Medium Express instructions. Prices in accordance with the declared value charges 2% of pay, but the price fee of not less than 100 yuan, and protect the price shall not exceed the amount of 10,000 won, and protect the price of the amount of more than 10,000 yuan, more than some invalid';
$_LANG['item_fee'] = 'Single commodity costs:';
$_LANG['base_fee'] = 'Cost less than 1000g';
$_LANG['step_fee'] = 'Every less than or equal to 1000g:';
$_LANG['shipping_print'] = "<table style=\"width:18.2cm\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td style=\"height:2.2cm;\">&nbsp;</td>\r\n  </tr>\r\n</table>\r\n<table style=\"width:18.2cm\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td style=\"height:4.4cm; width:9.1cm;\">\r\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n    <tr>\r\n    <td style=\"width:2cm; height:0.8cm;\">&nbsp;</td>\r\n    <td style=\"width:2.7cm;\">{\$shop_name}</td>\r\n    <td style=\"width:1.2cm;\">&nbsp;</td>\r\n    <td>{\$province}</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td colspan=\"3\" style=\"height:1.6cm;\">{\$shop_address}</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td colspan=\"3\" style=\"height:0.8cm;\">{\$shop_name}</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:1.2cm;\">{\$service_phone}</td>\r\n    <td>&nbsp;</td>\r\n    <td>&nbsp;</td>\r\n    </tr>\r\n    </table>\r\n    </td>\r\n    <td style=\"height:4.4cm; width:9.1cm;\">\r\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n    <tr>\r\n    <td style=\"width:2cm; height:0.8cm;\">&nbsp;</td>\r\n    <td style=\"width:2.7cm;\">{\$order.consignee}</td>\r\n    <td style=\"width:1.2cm;\">&nbsp;</td>\r\n    <td>{\$order.region}</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td colspan=\"3\" style=\"height:1.6cm;\">{\$order.address}</td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td colspan=\"3\" style=\"height:0.8cm;\"></td>\r\n    </tr>\r\n    <tr>\r\n    <td>&nbsp;</td>\r\n    <td style=\"height:1.2cm;\">{\$order.mobile}</td>\r\n    <td>&nbsp;</td>\r\n    <td>{\$order.zipcode}</td>\r\n    </tr>\r\n    </table>\r\n    </td>\r\n  </tr>\r\n</table>\r\n<table style=\"width:18.2cm\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n  <tr>\r\n    <td style=\"height:4.2cm;\">&nbsp;</td>\r\n  </tr>\r\n</table>";

?>
